# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynoquiz', '0005_quiz_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='dynoquiz.Choice'),
        ),
    ]
