# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynoquiz', '0007_auto_20160621_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(blank=True, help_text=b'Users the quiz is shared with.', related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
