# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynoquiz', '0008_auto_20160623_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='users',
        ),
    ]
