# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-25 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynoquiz', '0011_quizscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guessed', to='dynoquiz.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='dynoquiz.Question')),
                ('quiz_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='dynoquiz.QuizScore')),
            ],
        ),
    ]
