# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynoquiz', '0012_questionattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
